### ISSUE TITLE
Invalid description error

### ISSUE THREAD

**Issue by LordDeatHunter** [felix2300/Spigot-RightClickHarvest#2]
Error log:
```
[11:20:35] [Server thread/WARN]: org.bukkit.plugin.InvalidPluginException: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[11:20:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:94)
[11:20:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414)
[11:20:35] [Server thread/WARN]: 	at PlugMan.jar//com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:294)
[11:20:35] [Server thread/WARN]: 	at PlugMan.jar//com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[11:20:35] [Server thread/WARN]: 	at PlugMan.jar//com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[11:20:35] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[11:20:35] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[11:20:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832)
[11:20:35] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:795)
[11:20:35] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518)
[11:20:35] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[11:20:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
[11:20:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[11:20:35] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:20:35] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[11:20:35] [Server thread/WARN]: Caused by: org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
[11:20:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:186)
[11:20:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:92)
[11:20:35] [Server thread/WARN]: 	... 14 more
[11:20:35] [Server thread/WARN]: Caused by: java.util.zip.ZipException: zip END header not found
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1441)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1225)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:240)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
[11:20:35] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:285)
[11:20:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:174)
[11:20:35] [Server thread/WARN]: 	... 15 more
```

**Comment by FelixHornberger** [comment]
I have seen your Pull request.
Trough working out that you can use the 1.16 Version for 1.17 without the need to change. I will delete the latest githubrelease and recommand to use the release 1.4
